version: "3.3"
services:
  asap-nginx:
    ports:
      - '80:80'
      - '443:443'
    networks: 
      - asap-network
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - ./www:/usr/share/nginx/html

networks:
  asap-network:
    driver: bridge
    external: true